swagger: '2.0'
info:
  title: OANDA v20 Positions API
  description: >-
    v20 Position-related definitions and endpoints used to manage Positions
    within an Account.
  contact:
    name: OANDA API Support
    url: http://developer.oanda.com/rest-live-v20/introduction/
    email: api@oanda.com
  license:
    name: MIT
    url: https://github.com/oanda/v20-openapi/blob/master/LICENSE.txt
  version: 3.0.14
basePath: /v3
produces:
- application/json
consumes:
- application/json
paths:
  /accounts/{accountID}/positions:
    get:
      summary: List Positions
      description: >-
        List all Positions for an Account. The Positions returned are for
        every instrument that has had a position during the lifetime of
        an the Account.
      operationId: list
      parameters:
      - $ref: primitives.yaml#/parameters/authorizationHeaderParam
      - $ref: account.yaml#/parameters/accountIDPathParam
      responses:
        '200':
          description: The Account's Positions are provided.
          schema:
            type: object
            properties:
              positions:
                type: array
                description: The list of Account Positions.
                items:
                  $ref: '#/definitions/Position'
              lastTransactionID:
                type: string
                description: >-
                  The ID of the most recent Transaction created for the
                  Account
                example: '1523'
                format: >-
                  String representation of the numerical OANDA-assigned
                  TransactionID
        '401':
          $ref: primitives.yaml#/responses/401
        '404':
          $ref: primitives.yaml#/responses/404
        '405':
          $ref: primitives.yaml#/responses/405
  /accounts/{accountID}/openPositions:
    get:
      summary: Open Positions
      description: >-
        List all open Positions for an Account. An open Position is a Position
        in an Account that currently has a Trade opened for it.
      operationId: listOpen
      parameters:
      - $ref: primitives.yaml#/parameters/authorizationHeaderParam
      - $ref: account.yaml#/parameters/accountIDPathParam
      responses:
        '200':
          description: The Account's open Positions are provided.
          schema:
            type: object
            properties:
              positions:
                type: array
                description: The list of open Positions in the Account.
                items:
                  $ref: '#/definitions/Position'
              lastTransactionID:
                type: string
                description: >-
                  The ID of the most recent Transaction created for the
                  Account
                example: '1523'
                format: >-
                  String representation of the numerical OANDA-assigned
                  TransactionID
        '401':
          $ref: primitives.yaml#/responses/401
        '404':
          $ref: primitives.yaml#/responses/404
        '405':
          $ref: primitives.yaml#/responses/405
  /accounts/{accountID}/positions/{instrument}:
    get:
      summary: Instrument Position
      description: >-
        Get the details of a single Instrument's Position in an Account.
        The Position may by open or not.
      operationId: get
      parameters:
      - $ref: primitives.yaml#/parameters/authorizationHeaderParam
      - $ref: account.yaml#/parameters/accountIDPathParam
      - $ref: instrument.yaml#/parameters/instrumentNamePathParam
      responses:
        '200':
          description: The Position is provided.
          schema:
            type: object
            properties:
              position:
                $ref: '#/definitions/Position'
                description: The requested Position.
              lastTransactionID:
                type: string
                description: >-
                  The ID of the most recent Transaction created for the
                  Account
                example: '1523'
                format: >-
                  String representation of the numerical OANDA-assigned
                  TransactionID
        '401':
          $ref: primitives.yaml#/responses/401
        '404':
          $ref: primitives.yaml#/responses/404
        '405':
          $ref: primitives.yaml#/responses/405
  /accounts/{accountID}/positions/{instrument}/close:
    put:
      summary: Close Position
      description: >-
        Closeout the open Position for a specific instrument in an Account.
      operationId: close
      parameters:
      - $ref: primitives.yaml#/parameters/authorizationHeaderParam
      - $ref: account.yaml#/parameters/accountIDPathParam
      - $ref: instrument.yaml#/parameters/instrumentNamePathParam
      - name: closePositionBody
        despcription: Representation of how to close the position
        in: body
        schema:
          type: object
          properties:
            longUnits:
              type: string
              description: >-
                Indication of how much of the long Position to closeout.
                Either the string "ALL", the string "NONE", or a DecimalNumber
                representing how many units of the long position to close
                using a PositionCloseout MarketOrder. The units specified
                must always be positive.
            longClientExtensions:
              $ref: transaction.yaml#/definitions/ClientExtensions
              description: >-
                The client extensions to add to the MarketOrder used to
                close the long position.
            shortUnits:
              type: string
              description: >-
                Indication of how much of the short Position to closeout.
                Either the string "ALL", the string "NONE", or a DecimalNumber
                representing how many units of the short position to close
                using a PositionCloseout MarketOrder. The units specified
                must always be positive.
            shortClientExtensions:
              $ref: transaction.yaml#/definitions/ClientExtensions
              description: >-
                The client extensions to add to the MarketOrder used to
                close the short position.
        required: true
      responses:
        '200':
          description: >-
            The Position closeout request has been successfully processed.
          headers:
            Location:
              description: A link to the Position that was just closed out
              type: string
          schema:
            type: object
            properties:
              longOrderCreateTransaction:
                $ref: transaction.yaml#/definitions/MarketOrderTransaction
                description: >-
                  The MarketOrderTransaction created to close the long Position.
              longOrderFillTransaction:
                $ref: transaction.yaml#/definitions/OrderFillTransaction
                description: OrderFill Transaction that closes the long
                  Position
              longOrderCancelTransaction:
                $ref: transaction.yaml#/definitions/OrderCancelTransaction
                description: >-
                  OrderCancel Transaction that cancels the MarketOrder created
                  to close the long Position
              shortOrderCreateTransaction:
                $ref: transaction.yaml#/definitions/MarketOrderTransaction
                description: >-
                  The MarketOrderTransaction created to close the short
                  Position.
              shortOrderFillTransaction:
                $ref: transaction.yaml#/definitions/OrderFillTransaction
                description: OrderFill Transaction that closes the short
                  Position
              shortOrderCancelTransaction:
                $ref: transaction.yaml#/definitions/OrderCancelTransaction
                description: >-
                  OrderCancel Transaction that cancels the MarketOrder created
                  to close the short Position
              relatedTransactionIDs:
                type: array
                description: >-
                  The IDs of all Transactions that were created while satisfying
                  the request.
                items:
                  $ref: transaction.yaml#/definitions/TransactionID
              lastTransactionID:
                type: string
                description: >-
                  The ID of the most recent Transaction created for the
                  Account
                example: '1523'
                format: >-
                  String representation of the numerical OANDA-assigned
                  TransactionID
        '400':
          description: >-
            The Parameters provided that describe the Position closeout
            are invalid.
          schema:
            type: object
            properties:
              longOrderRejectTransaction:
                $ref: transaction.yaml#/definitions/MarketOrderRejectTransaction
                description: >-
                  The Transaction created that rejects the creation of a
                  MarketOrder to close the long Position.
              shortOrderRejectTransaction:
                $ref: transaction.yaml#/definitions/MarketOrderRejectTransaction
                description: >-
                  The Transaction created that rejects the creation of a
                  MarketOrder to close the short Position.
              relatedTransactionIDs:
                type: array
                description: >-
                  The IDs of all Transactions that were created while satisfying
                  the request.
                items:
                  $ref: transaction.yaml#/definitions/TransactionID
              lastTransactionID:
                type: string
                description: >-
                  The ID of the most recent Transaction created for the
                  Account
                example: '1523'
                format: >-
                  String representation of the numerical OANDA-assigned
                  TransactionID
              errorCode:
                type: string
                description: >-
                  The code of the error that has occurred. This field may
                  not be returned for some errors.
                required: false
              errorMessage:
                type: string
                description: >-
                  The human-readable description of the error that has occurred.
                required: true
        '401':
          $ref: primitives.yaml#/responses/401
        '404':
          $ref: primitives.yaml#/responses/404
        '405':
          $ref: primitives.yaml#/responses/405
definitions:
  Position:
    type: object
    description: The specification of a Position within an Account.
    properties:
      instrument:
        type: string
        description: The Position's Instrument.
        format: >-
          A string containing the base currency and quote currency delimited
          by a "_".
      pl:
        type: string
        description: >-
          Profit/loss realized by the Position over the lifetime of the
          Account.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      unrealizedPL:
        type: string
        description: >-
          The unrealized profit/loss of all open Trades that contribute
          to this Position.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      resettablePL:
        type: string
        description: >-
          Profit/loss realized by the Position since the Account's resettablePL
          was last reset by the client.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      long:
        $ref: '#/definitions/PositionSide'
        description: The details of the long side of the Position.
      short:
        $ref: '#/definitions/PositionSide'
        description: The details of the short side of the Position.
  PositionSide:
    type: object
    description: >-
      The representation of a Position for a single direction (long or short).
    properties:
      units:
        type: string
        description: >-
          Number of units in the position (negative value indicates short
          position, positive indicates long position).
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on what the number represents.
      averagePrice:
        type: string
        description: >-
          Volume-weighted average of the underlying Trade open prices for
          the Position.
        format: >-
          A decimal number encodes as a string. The amount of precision
          provided depends on the Price's Instrument.
      tradeIDs:
        type: array
        description: >-
          List of the open Trade IDs which contribute to the open Position.
        items:
          $ref: trade.yaml#/definitions/TradeID
      pl:
        type: string
        description: >-
          Profit/loss realized by the PositionSide over the lifetime of
          the Account.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      unrealizedPL:
        type: string
        description: >-
          The unrealized profit/loss of all open Trades that contribute
          to this PositionSide.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      resettablePL:
        type: string
        description: >-
          Profit/loss realized by the PositionSide since the Account's resettablePL
          was last reset by the client.
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
  CalculatedPositionState:
    type: object
    description: The dynamic (calculated) state of a Position
    properties:
      instrument:
        type: string
        description: The Position's Instrument.
        format: >-
          A string containing the base currency and quote currency delimited
          by a "_".
      netUnrealizedPL:
        type: string
        description: The Position's net unrealized profit/loss
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      longUnrealizedPL:
        type: string
        description: >-
          The unrealized profit/loss of the Position's long open Trades
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
      shortUnrealizedPL:
        type: string
        description: >-
          The unrealized profit/loss of the Position's short open Trades
        format: >-
          A decimal number encoded as a string. The amount of precision
          provided depends on the Account's home currency.
parameters:
  orderSpecifierPathParam:
    name: orderSpecifier
    despcription: The Order Specifier
    in: path
    type: string
    format: >-
      Either the Order's OANDA-assigned OrderID or the Order's client-provided
      ClientID prefixed by the "@" symbol
    required: true

