swagger: '2.0'
info:
  title: OANDA v20 Site API
  description: >-
    Site-related definitions and endpoints. These endpoints are for internal,
    administrative access to Site-level services.
  contact:
    name: OANDA API Support
    url: http://developer.oanda.com/rest-live-v20/introduction/
    email: api@oanda.com
  license:
    name: MIT
    url: https://github.com/oanda/v20-openapi/blob/master/LICENSE.txt
  version: 3.0.22
basePath: /v3
produces:
- application/json
consumes:
- application/json
paths:
  /accounts/{accountID}/pricing:
    get:
      summary: Current Account Prices
      description: >-
        Get pricing information for a specified list of Instruments within
        an Account.
      operationId: get
      parameters:
      - $ref: v20_primitives.json#/parameters/authorizationHeaderParam
      - $ref: >-
          v20_primitives.json#/parameters/acceptDatetimeFormatHeaderParam
      - $ref: v20_account.json#/parameters/accountIDPathParam
      - name: instruments
        description: List of Instruments to get pricing for.
        in: query
        type: array
        items:
          type: string
          format: >-
            A string containing the base currency and quote currency delimited
            by a "_".
        collectionFormat: csv
        required: true
      - name: since
        description: >-
          Date/Time filter to apply to the response. Only prices and home
          conversions (if requested) with a time later than this filter
          (i.e. the price has changed after the since time) will be provided,
          and are filtered independently.
        in: query
        type: string
        format: >-
          The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt.
          The Unix representation is a string representing the number of
          seconds since the Unix Epoch (January 1st, 1970 at UTC). The value
          is a fractional number, where the fractional part represents a
          fraction of a second (up to nine decimal places).
      - name: includeUnitsAvailable
        description: >-
          Flag that enables the inclusion of the unitsAvailable field in
          the returned Price objects.
        in: query
        type: boolean
      - name: includeHomeConversions
        description: >-
          Flag that enables the inclusion of the homeConversions field in
          the returned response. An entry will be returned for each currency
          in the set of all base and quote currencies present in the requested
          instruments list.
        in: query
        type: boolean
      responses:
        '200':
          description: Pricing information has been successfully provided.
          headers:
            RequestID:
              description: The unique identifier generated for the request
              type: string
          schema:
            type: object
            properties:
              prices:
                type: array
                description: The list of Price objects requested.
                items:
                  $ref: '#/definitions/Price'
              homeConversions:
                type: array
                description: >-
                  The list of home currency conversion factors requested.
                  This field will only be present if includeHomeConversions
                  was set to true in the request.
                items:
                  $ref: '#/definitions/HomeConversions'
              time:
                type: string
                description: >-
                  The DateTime value to use for the "since" parameter in
                  the next poll request.
                format: >-
                  The RFC 3339 representation is a string conforming to
                  https://tools.ietf.org/rfc/rfc3339.txt. The Unix representation
                  is a string representing the number of seconds since the
                  Unix Epoch (January 1st, 1970 at UTC). The value is a
                  fractional number, where the fractional part represents
                  a fraction of a second (up to nine decimal places).
        '400':
          $ref: v20_primitives.json#/responses/400
        '401':
          $ref: v20_primitives.json#/responses/401
        '404':
          $ref: v20_primitives.json#/responses/404
        '405':
          $ref: v20_primitives.json#/responses/405
  /accounts/{accountID}/pricing/stream:
    get:
      summary: Price Stream
      description: >-
        Get a stream of Account Prices starting from when the request is
        made.

        This pricing stream does not include every single price created
        for the Account, but instead will provide at most 4 prices per second
        (every 250 milliseconds) for each instrument being requested.

        If more than one price is created for an instrument during the 250
        millisecond window, only the price in effect at the end of the window
        is sent. This means that during periods of rapid price movement,
        subscribers to this stream will not be sent every price.

        Pricing windows for different connections to the price stream are
        not all aligned in the same way (i.e. they are not all aligned to
        the top of the second). This means that during periods of rapid
        price movement, different subscribers may observe different prices
        depending on their alignment.
      operationId: stream
      parameters:
      - $ref: v20_primitives.json#/parameters/authorizationHeaderParam
      - $ref: >-
          v20_primitives.json#/parameters/acceptDatetimeFormatHeaderParam
      - $ref: v20_account.json#/parameters/accountIDPathParam
      - name: instruments
        description: List of Instruments to stream Prices for.
        in: query
        type: array
        items:
          type: string
          format: >-
            A string containing the base currency and quote currency delimited
            by a "_".
        collectionFormat: csv
        required: true
      - name: snapshot
        description: >-
          Flag that enables/disables the sending of a pricing snapshot when
          initially connecting to the stream.
        in: query
        type: boolean
      responses:
        '200':
          description: Connecting to the Price Stream was successful.
          headers:
            Link:
              description: A link to the next/previous order book snapshot.
              type: string
            RequestID:
              description: The unique identifier generated for the request
              type: string
          schema:
            type: object
            description: >-
              The response body for the Pricing Stream uses chunked transfer
              encoding.  Each chunk contains Price and/or PricingHeartbeat
              objects encoded as JSON.  Each JSON object is serialized into
              a single line of text, and multiple objects found in the same
              chunk are separated by newlines.

              Heartbeats are sent every 5 seconds.
            properties:
              price:
                $ref: '#/definitions/Price'
              heartbeat:
                $ref: '#/definitions/PricingHeartbeat'
        '400':
          $ref: v20_primitives.json#/responses/400
        '401':
          $ref: v20_primitives.json#/responses/401
        '404':
          $ref: v20_primitives.json#/responses/404
        '405':
          $ref: v20_primitives.json#/responses/405
definitions:
  MT4TransactionHeartbeat:
    type: object
    description: >-
      A TransactionHeartbeat object is injected into the Transaction stream
      to ensure that the HTTP connection remains active.
    properties:
      type:
        type: string
        description: The string "HEARTBEAT"
      time:
        type: string
        description: The date/time when the TransactionHeartbeat was created.
        format: >-
          The RFC 3339 representation is a string conforming to https://tools.ietf.org/rfc/rfc3339.txt.
          The Unix representation is a string representing the number of
          seconds since the Unix Epoch (January 1st, 1970 at UTC). The value
          is a fractional number, where the fractional part represents a
          fraction of a second (up to nine decimal places).
parameters:
  mt4ServerIDPathParam:
    name: mt4ServerID
    description: MT4 Server ID
    in: path
    type: int
    required: true
responses:
  '400':
    description: >-
      Bad Request. The client has provided invalid data to be processed
      by the server.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.
  '401':
    description: >-
      Unauthorized. The endpoint being access required the client to authenticated,
      however the the authentication token is invalid or has not been provided.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.
  '403':
    description: >-
      Forbidden. The client has provided a token that does not authorize
      them to perform the action implemented by the API endpoint.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.
  '404':
    description: >-
      Not Found. The client has attempted to access an entity that does
      not exist.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.
  '405':
    description: >-
      Method Not Allowed. The client has attempted to access an endpoint
      using an HTTP method that is not supported.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.
  '416':
    description: >-
      Range Not Satisfiable. The client has specified a range that is invalid
      or cannot be processed.
    headers:
      RequestID:
        description: The unique identifier generated for the request
        type: string
    schema:
      type: object
      properties:
        errorCode:
          type: string
          description: >-
            The code of the error that has occurred. This field may not
            be returned for some errors.
        errorMessage:
          type: string
          description: >-
            The human-readable description of the error that has occurred.

